import { type RouteConfig, route, index, layout, prefix } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("setup", "routes/setup.tsx"),
  route("auth/login", "routes/auth/login.tsx"),
  route("auth/sign-up", "routes/auth/sign-up.tsx"),
  layout("routes/dashboard/layout.tsx", [
    route("dashboard", "routes/dashboard/index.tsx"),
    route("dashboard/settings", "routes/dashboard/settings.tsx"),
    route("dashboard/short-links", "routes/dashboard/short-links.tsx"),
    route("dashboard/admin", "routes/dashboard/admin.tsx"),
  ]),
  route("v/:fileName", "routes/viewer.tsx"),
  route("r/:fileName", "routes/viewer-raw.tsx"),
  route("u/:username", "routes/user-viewer.tsx"),
  route("u/:username/:fileName", "routes/user-viewer.tsx", { id: "user-viewer-file" }),
  // API routes
  route("api/setup/config", "routes/api/setup.config.tsx"),
  route("api/auth/login", "routes/api/auth.login.tsx"),
  route("api/auth/signup", "routes/api/auth.signup.tsx"),
  route("api/auth/logout", "routes/api/auth.logout.tsx"),
  route("api/upload", "routes/api/upload.tsx"),
  route("api/uploads/:id", "routes/api/uploads.$id.tsx"),
  route("api/delete/:id", "routes/api/delete.$id.tsx"),
  route("api/trash", "routes/api/trash.tsx"),
  route("api/trash/cleanup", "routes/api/trash.cleanup.tsx"),
  route("api/tokens", "routes/api/tokens.tsx"),
  route("api/user/settings", "routes/api/user.settings.tsx"),
  route("api/user/avatar", "routes/api/user.avatar.tsx"),
  route("api/admin/system-settings", "routes/api/admin.system-settings.tsx"),
  route("api/admin/users/:userId", "routes/api/admin.users.$userId.tsx"),
  route("api/admin/users/create", "routes/api/admin.users.create.tsx"),
  route("api/admin/webhooks", "routes/api/admin.webhooks.tsx"),
  route("api/admin/invites", "routes/api/admin.invites.tsx"),
  route("api/admin/audit", "routes/api/admin.audit.tsx"),
  route("api/admin/analytics", "routes/api/admin.analytics.tsx"),
  route("api/admin/features", "routes/api/admin.features.tsx"),
  route("api/folders", "routes/api/folders.tsx"),
  route("api/verify-password", "routes/api/verify-password.tsx"),
  route("api/download-zip", "routes/api/download-zip.tsx"),
  route("api/system-settings/public", "routes/api/system-settings.public.tsx"),
  route("api/logo", "routes/api/logo.tsx"),
  route("api/files/*", "routes/api/files.tsx"),
  route("api/raw/:fileName", "routes/api/raw.$fileName.tsx"),
  route("api/thumb/:id", "routes/api/thumb.$id.tsx"),
  route("api/short-links", "routes/api/short-links.tsx"),
  route("s/:code", "routes/s.$code.tsx"),
  // Custom path catch-all (must be last)
  route(":customPath", "routes/custom-path.tsx"),
  route(":customPath/:fileName", "routes/custom-path.tsx", { id: "custom-path-file" }),
] satisfies RouteConfig;
